dinner/urls.py
from django.urls import path

from . import views

app_name = 'dinner'

urlpatterns = [
    path('', views.Homepage.as_view(), name='index'),
    path('add/', views.AddDin.as_view(), name='addDinner'),
    path('details/', views.DinnerDetailsView.as_view(), name='details')
]

dinner/models.py
from django.db import models


# Create your models here.

class Options(models.Model):
    dinner_name = models.CharField(max_length=240)
    dinner_ingredients = models.CharField(max_length=240)
    dinner_instructions = models.CharField(max_length=240)

    def __str__(self):
        return self.dinner_name

dinner/forms.py
from django.forms import ModelForm

from dinner.models import Options


class AddOptions(ModelForm):
    class Meta:
        model = Options
        fields = ['dinner_name', 'dinner_ingredients', 'dinner_instructions']

dinner/views.py
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views import View

from dinner.forms import AddOptions
from dinner.models import Options


def index(request):
    return render(request, 'dinner/home_page.html', {})


class Homepage(View):
    template_name = 'dinner/home_page.html'

    dinner_formset = modelformset_factory(
        fields=('dinner_name',),
        extra=0,
        model=Options
    )

    def get(self, request):
        formset = self.dinner_formset()
        context = {'formset': formset}
        return render(request, self.template_name, context)


class AddDin(View):
    template_name = 'dinner/add_dinner.html'
    form_class = AddOptions

    def get(self, request):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('dinner:index'))

        context = {'form': form}
        return render(request, self.template_name, context)


class DinnerDetailsView(View):
    template_name = 'dinner/dinner_details.html'
    form_class = AddOptions

    def get(self, request):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

dinner/templates/dinner/add_dinner.html
{% extends 'dinner/base_with_header.html' %}

{% block body %}
    <div class="row"></div>
    <div class="container">
        <form action="" method="post" style="background: blanchedalmond">
            {% csrf_token %}
            {{ form }}
            <input class="btn right" type="submit" value="submit">
        </form>
    </div>
{% endblock body %}

dinner/templates/dinner/base.html
<html>

<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    {% block head %}
    {% endblock head %}
</head>

<body>

{% block body_header %}
{% endblock body_header %}

{% block body %}
{% endblock body %}


<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

{% block scripts %}
{% endblock scripts %}

</body>
</html>

dinner/templates/dinner/base_with_header.html
{% extends 'dinner/base.html' %}

{% block body_header %}
    <nav>
        <div class="nav-wrapper">
            <a href="{% url 'dinner:index' %}" class="brand-logo center">What's For dinner</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'dinner:addDinner' %}">Add Dinner Option</a></li>
            </ul>
        </div>
    </nav>
{% endblock body_header %}

dinner/templates/dinner/dinner_details.html
{% extends 'dinner/base_with_header.html' %}

{% block body %}

{% endblock body %}

dinner/templates/dinner/home_page.html
{% extends "dinner/base_with_header.html" %}

{% block body %}
    <form method="get">
        {{ formset.management_form }}
        {% for form in formset %}
            <div class="row">
                <div class="col s12 m4">
                    <div class="card horizontal">
                        <div class="card-image">
                            <img src="https://lorempixel.com/100/190/nature/6">
                        </div>
                        <div class="card-stacked">
                            <div class="card-content">
                                <h3>{{ form.dinner_name.value }}</h3>
                                <p>List of ingredients</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </form>
{% endblock body %}